=== HeinKhantZaw/smartcampus.gamification/GamificationEngine/src/main/webapp/WEB-INF/specifications/gamifiableActions/gamifiableActions.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <!-- Enumerations -->
    <xs:simpleType name="param-type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="String"/>
            <xs:enumeration value="Integer"/>
            <xs:enumeration value="Boolean"/>
            <xs:enumeration value="Date"/>
            <xs:enumeration value="Time"/>
        </xs:restriction>
    </xs:simpleType>
        

    <!-- Gamifiable actions -->
    <xs:element name="gamifiable-actions">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="action" maxOccurs="unbounded" minOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="action">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="description" type="xs:string"/>
                
                <xs:element ref="params" maxOccurs="1" minOccurs="0"/>
            </xs:sequence>
            
            <xs:attribute type="xs:string" name="id" use="required" />
        </xs:complexType>
    </xs:element>
    
    <xs:element name="params">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="basic-param" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="enumeration-param" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="composite-param" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="basic-param">
        <xs:complexType>
            <xs:attribute type="xs:string" name="name" use="required"/>
            <xs:attribute type="xs:string" name="id" use="optional"/>
            <xs:attribute type="param-type" name="type" use="required"/>
        </xs:complexType>
    </xs:element>
  
    <xs:element name="composite-param">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="basic-param" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="enumeration-param" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="composite-param" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            
            <xs:attribute type="xs:string" name="name" use="required"/>
            <xs:attribute type="xs:string" name="id" use="optional"/>
        </xs:complexType>
    </xs:element>
  
    <xs:element name="enumeration-param">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="enum-entry" maxOccurs="unbounded" minOccurs="1"/>
            </xs:sequence>
            
            <xs:attribute type="xs:string" name="name"/>
            <xs:attribute type="xs:string" name="id"/>
        </xs:complexType>
    </xs:element>
  
    <xs:element name="enum-entry">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute type="xs:string" name="name" use="optional"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== HeinKhantZaw/smartcampus.gamification/GamificationEngine/src/main/webapp/WEB-INF/specifications/gamifiableActions/gamifiableActionsViaggiaRovereto.xml
<?xml version="1.0" encoding="UTF-8"?>
    
<gamifiable-actions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:noNamespaceSchemaLocation="gamifiableActions.xsd">
    
    <action id="1">
        <name>BusDelayReporting</name>
        <description>The user has reported the delay of a bus</description>
    </action>
    
    <action id="2">
        <name>BusServiceRating</name>
        <description>The user has rated the bus service quality</description>
    </action>
    
    <action id="3">
        <name>BusCommentAdding</name>
        <description>The user has commented the bus service</description>
    </action>
    
    <action id="4">
        <name>ItenerarySaving</name>
        <description>The user has saved an interary</description>
        
        <params>
            <composite-param name="itinerary" id="">
                <basic-param name="numberOfMeans" id="" type="Integer"/>
                
                <enumeration-param name="means" id="">
                    <enum-entry name="BIKE"/>
                    <enum-entry name="CAR"/>
                    <enum-entry name="BUS"/>
                </enumeration-param>
                
                <composite-param name="KM" id="">
                    <basic-param name="totalKM" id="" type="Integer" />
                    <basic-param name="bikeKM" id="" type="Integer"/>
                    <basic-param name="carKM" id="" type="Integer"/>
                    <basic-param name="busKM" id="" type="Integer"/>
                </composite-param>
            </composite-param>
        </params>
    </action>
    
    <action id="5">
        <name>BikeUsage</name>
        <description>The user has used a bike</description>
        
        <params>
            <basic-param name="bikeKM" id="" type="Integer"/>
        </params>
    </action>
    
    <action id="6">
        <name>CarUsage</name>
        <description>The user has used a car</description>
        
        <params>
            <basic-param name="carKM" id="" type="Integer"/>
        </params>
    </action>
    
    <action id="7">
        <name>BusUsage</name>
        <description>The user has used a bus</description>
        
        <params>
            <basic-param name="busKM" id="" type="Integer"/>
        </params>
    </action>
</gamifiable-actions>
